crytic/blockchain-security-contacts

README.md

Added a contact and bug bounty to MetaMask

---

README.md

If you need any verification, you can email security@binance.com and I will reply from there. Thanks!

Added Binance and Trustwallet details

---

README.md

If there are any further questions, please reach out to the team security@brickblock.io
Thanks for setting up this listing :)

add Brickblock details

---

README.md

Added Polymath details to the list.

Added Polymath details

---

README.md

Add Arkane inside the wallets chapter

Add Arkane inside wallets chapter

---

README.md

Verification: this email is listed on the [official web page](https://www.bitstamp.net/) in the footer.

Add Bitstamp exchange

---

README.md

Add Amoveo Exchange

---

README.md

Add nahmii to the list of decentralized applications and sort the list alphabetically. 
Add HBT and NII tokens to the list of ERC20 tokens.

Add nahmii dApp and HBT and NII tokens

---

README.md

Our website can be found at: https://iov.one

Add IOV and email to blockchains list

---

README.md

Add contact for DAI/makerdao

---

README.md

From https://github.com/ethsecurity/contact-info/pull/2

Added status

---

README.md

Updated Loom Network

---

README.md

Coinfinity.co is an austrian-based Ether and cryptocurrency broker.
You can verifiy the email addres and the pgp link on the official [Security page](https://coinfinity.co/responsible-disclosure/).

Adding security contact for coinfinity.co (broker, service provider)

---

README.md

Update Amoveo Exchange to A1 Exchange

---

README.md

Added POA Core, xDai Chain, POA20 Bridge from https://poa.net

Add POA Core, xDai Chain, POA20 Bridge

---

README.md

- Add [Airswap](https://www.airswap.io) to the DEX subsection
- Add bounty emails

Airswap Update

---

README.md

Thanks for putting this list together! :)
For reference, we're a project that builds DAOs and apps to help open source communities raise funds, make decisions, and sustainably support their communities.
- https://1hive.org/

Adding 1Hive

---

README.md

Add Upvest security contacts

---

README.md

See smart contract or dumb contract for validation
https://github.com/erasureprotocol/erasure-protocol/blob/master/contracts/agreements/CountdownGriefing.sol

Add Numerai security contacts

---

README.md

C-Layer is a multi token framework with a main focus on executing DeFi compliance on-chain.
We currently have two sets of token core deployed on the mainnet:
0x14cA4d241D6061775cFe82A24e90b2b7Db822aDb
0xF0C57e93Bd88CF45697a29B5f184768783531966
I am welcoming feedbacks about my PR.

Adding C-Layer to the contact list

---

README.md

Nexus Mutual is a ethereum based mutual platform, launching soon. More details at https://nexusmutual.io/

Added Nexus Mutual to decentralized applications

---

README.md

added QuikNode.io

---

README.md

Added DDEX to the DEX section, with our security email. Added in alphabetical order

Adding DDEX to the DEX's

---

README.md

Adds InstaDApp contact email address and the external reference of Github repo of our contracts.

Added InstaDApp Contact and Contracts Link.

---

README.md

see footer at https://edgewa.re for link

Added Edgeware and Commonwealth.im contact

---

README.md

I have added Leverj exchange and its related Tokens (FEE and LEV). Please merge it.

added leverj.io exchange and tokens (FEE, LEV)

---

README.md

Add Idle Finance security contact and deployed addresses link

NEW: add Idle Finance

---

README.md

Please reference the github readme page for verification:
https://github.com/ampleforth/uFragments/blob/master/README.md

Add Ample security contact info

---

README.md

We would like to add AAVE as a contact, thank you

add aave as a contact

---

README.md

Hi!
As we approach the launch of out IDO platform [Lemonade](https://lemonadefi.com) with the debut of $STAK campaign, I'm expanding the repo with our contact information.
I'm Kaue, Lead Ethereum Developer for [Jigstack](https://jigstack.org), and I'm happy to help with any other steps necessary. Thanks!

Add Jigstack $STAK Governance Token

---

README.md

This is the dedicated contact for security related matters @ bitstamp.

Update README - bitstamp contact

---

README.md

Added [ReFi's](https://www.reimagined.fi/security) security contact details

Added ReFi's security contact details

---

README.md

Proof: https://twitter.com/SovrynBTC/status/1367029820123713536

Add Sovryn bug bounty info

---

README.md

Added Immutable X token and Gods Unchained contact details.

Added Immutable X and Gods Unchained

---

README.md

Added Auroracoin contact.   See en.auroracoin.is for verification of mikael hannes

Add Auroracoin

---

README.md

This PR adds Lopeer exchange security contact to the list

Add Lopeer Exchange
